version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/clang_api_doc
    steps:
      - checkout
      - run:
          name: poetry installation
          command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
      - run:
          name: install
          command: $HOME/.poetry/bin/poetry install
      # - run:
      #     name: tests
      #     command: poetry run pytest
      - run:
          name: package
          command: $HOME/.poetry/bin/poetry build
      - run:
          name: publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              $HOME/.poetry/bin/poetry config http-basic.pypi $PYPIUSER $PYPIPASSWORD
              $HOME/.poetry/bin/poetry publish
            fi